-- ---------------------------------------------------------------------------
-- HPE Morpheus Coffee Club schema.
--
-- The table is created explicitly rather than being generated by Hibernate so
-- that the physical column order matches the agreed contract:
--   order_date, name, drink, price, total_paid_today, is_removed
-- Hibernate's ddl-auto emits columns alphabetically and offers no way to
-- control their order, so the DDL lives here and Hibernate is limited to
-- validating that the entity still matches (spring.jpa.hibernate.ddl-auto).
--
-- Idempotent: re-running on an existing database is a no-op.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hpe_morpheus_coffee_club (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    order_date       DATE          NOT NULL,
    name             VARCHAR(60)   NOT NULL,
    drink            VARCHAR(80)   NOT NULL,
    price            NUMERIC(8, 2) NOT NULL,
    total_paid_today NUMERIC(10, 2) NOT NULL,
    is_removed       VARCHAR(1)    NOT NULL,
    CONSTRAINT pk_hpe_morpheus_coffee_club PRIMARY KEY (id)
);

-- Pre-population and the fairness ledger both read by person, newest first.
CREATE INDEX IF NOT EXISTS ix_coffee_club_order_date ON hpe_morpheus_coffee_club (order_date DESC);
CREATE INDEX IF NOT EXISTS ix_coffee_club_name ON hpe_morpheus_coffee_club (name);
