-- ---------------------------------------------------------------------------
-- HPE Morpheus Coffee Club schema.
--
-- The table is created explicitly rather than being generated by Hibernate so
-- that the physical column order matches the agreed contract:
--   order_date, name, drink, price, total_paid_today, is_removed
-- Hibernate's ddl-auto emits columns alphabetically and offers no way to
-- control their order, so the DDL lives here and Hibernate is limited to
-- validating that the entity still matches (spring.jpa.hibernate.ddl-auto).
--
-- Idempotent: re-running on an existing database is a no-op.
--
-- Portability. The column types (DATE, VARCHAR(n), NUMERIC(p,s)), the named
-- PRIMARY KEY constraint and GENERATED BY DEFAULT AS IDENTITY are all ISO SQL,
-- so this runs unchanged on H2 and PostgreSQL 10+. Two constructs are vendor
-- extensions rather than standard, and both are deliberate — the scripts run on
-- every startup, so they have to be re-runnable:
--   * CREATE TABLE IF NOT EXISTS   — also MySQL, MariaDB, SQLite; Oracle,
--                                    SQL Server and DB2 have no equivalent.
--   * CREATE INDEX IF NOT EXISTS   — also SQLite; not MySQL, Oracle or
--                                    SQL Server.
-- Porting to one of those engines means guarding object creation another way
-- (a catalog check, or a migration tool such as Flyway or Liquibase) and, for
-- MySQL and SQL Server, swapping the identity clause for their own syntax.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hpe_morpheus_coffee_club (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    order_date       DATE          NOT NULL,
    name             VARCHAR(60)   NOT NULL,
    drink            VARCHAR(80)   NOT NULL,
    price            NUMERIC(8, 2) NOT NULL,
    total_paid_today NUMERIC(10, 2) NOT NULL,
    is_removed       VARCHAR(1)    NOT NULL,
    CONSTRAINT pk_hpe_morpheus_coffee_club PRIMARY KEY (id)
);

-- Pre-population and the fairness ledger both read by person, newest first.
CREATE INDEX IF NOT EXISTS ix_coffee_club_order_date ON hpe_morpheus_coffee_club (order_date DESC);
CREATE INDEX IF NOT EXISTS ix_coffee_club_name ON hpe_morpheus_coffee_club (name);
